In [1]:
import numpy as np
from sympy import *

## № 1

**1**

In [2]:
# функция, расчитывающая скалярное произведение
def mult_(a,b):
    if len (a) == len (b):
        mult = 0
        for i in range(len(a)):
            mult += a[i] * b[i]
    else:
        mult = 'нет решения, т.к. размерности массивов разные'
                
    return (mult)

In [3]:
a = [2, 5, 0, 6, 8, 10, 6, 7, 5, 7]
b = [8, 6, 7, 9, 6, 6, 2, 3, 2, 3]

In [4]:
 mult_(a,b) * 3 * 2

1632

In [5]:
# или так
a = np.array(a)
b = np.array(b)

In [6]:
3 * 2 * np.dot(a,b)

1632

**2**

In [7]:
a = [9, 6, 7, 7, 0, 1, 6, 8, 1, 2]
b = [0, 2, 2, 6, 7, 8, 8, 3, 1, 8]

In [8]:
mult_(a,b) * 6 * 5

4950

**3**

In [9]:
a = [2, 5, 0, 6, 8, 1, 0, 6, 7, 5, 7]
b = [8, 6, 7, 9, 6, 6, 2, 3, 2, 3]

In [10]:
 mult_(a,b)

'нет решения, т.к. размерности массивов разные'

**4**

In [11]:
a = [9, 6, 7, 7, 0, 1, 6, 8, 1, 2]
b = [0, 2, 2, 6, 7, 8, 8, 3, 1, 8]

In [12]:
 mult_(a,b)

165

## № 2

**5**

In [13]:
# функция транспонирования
def transp_(a):
    n = a.shape[0]
    m = a.shape[1]
    b = np.zeros ((m, n))
    for i in range(m):
        for j in range(n):
            b[i][j] = a[j][i]
    return(b)

    

In [14]:
a = np.array([[2, 1, 7, 4], [5, 6, 7, 3], [9, 8, 2, 12], [11, 14, 15, 15]])
transp_(a)

array([[ 2.,  5.,  9., 11.],
       [ 1.,  6.,  8., 14.],
       [ 7.,  7.,  2., 15.],
       [ 4.,  3., 12., 15.]])

In [15]:
# или так
a.transpose()

array([[ 2,  5,  9, 11],
       [ 1,  6,  8, 14],
       [ 7,  7,  2, 15],
       [ 4,  3, 12, 15]])

**6**

In [16]:
a = np.array([[3, 7, 8, 3, 6],[2, 5, 9, 4, 13]])
transp_(a)

array([[ 3.,  2.],
       [ 7.,  5.],
       [ 8.,  9.],
       [ 3.,  4.],
       [ 6., 13.]])

In [17]:
# или так
a.transpose()

array([[ 3,  2],
       [ 7,  5],
       [ 8,  9],
       [ 3,  4],
       [ 6, 13]])

## № 3

In [25]:
a1, a2 = symbols ('a1, a2')

In [26]:
# среднеквадратичная ошибка
MSE = 1 / 4 * ((a1 * 1 + a2 * 2 - 5) **2 + (a1 * 5 + a2 * 3 - 6) **2 + (a1 * 2 + a2 * 4 - 10) **2 + \
(a1 * 3 + a2 * 7 - 8) **2 )

In [27]:
# веса
a = np.array([a1, a2])
a

array([a1, a2], dtype=object)

In [28]:
# градиент ошибки
d_MSE = np.array([])
for i in range(len (a)):
    d_MSE = np.append (d_MSE, diff(MSE, a[i]))
    
d_MSE

array([19.5*a1 + 23.0*a2 - 39.5, 23.0*a1 + 39.0*a2 - 62.0], dtype=object)

In [29]:
x0 = np.zeros ((len(a))) # начальная точка
l = 0.01 # шаг 
num = 0 # итерации

In [30]:
# градиентный спуск
while True:
    num += 1
    d_MSE_=[]
    for i in range(len (a)):
        d_MSE_ = np.append (d_MSE_, d_MSE[i].subs ({a[0]:x0[0], a[1]:x0[1]})) # подставляем в градиент значения а
        
    x0 = x0 - l * d_MSE_ # вычисляем новые значения а
     
    MSE_= MSE.subs({a[0]:x0[0], a[1]:x0[1] }) # вычисление среднеквадратичной ошибки 
    
    #print(MSE_)
    if MSE_ < 6.36:
        print ('количество итераций = ', num, '\n', 'MSE = ', MSE_)
        break

    

количество итераций =  7 
 MSE =  6.35010849011797


In [31]:
# for i in range (len (a)):
#     if i == 0:
#         MSE_ = MSE.subs(a[i],x0[i])
#     else:
#         MSE_ = MSE_.subs(a[i],x0[i])
# MSE_